git:
    default_branch: main
worktree:
    enabled: true
    base_dir: ./.worktrees
    init_commands:
        - git status
    auto_operations:
        create_on_start: true
        remove_on_close: true
        cleanup_orphaned: true
tickets:
    dir: tickets
    todo_dir: todo
    doing_dir: doing
    done_dir: done
    template: |-
        # Ticket Overview

        Write the overview and tasks for this ticket here.

        ## Tasks
        - [ ] task1
        - [ ] task2
        - [ ] task3
        - [ ] Run `make test` to run the tests
        - [ ] Run `make vet`, `make fmt` and `make lint`
        - [ ] Update documentation if necessary
        - [ ] Update README.*.md
        - [ ] Get developer approval before closing

        ## Notes

        Additional notes or requirements.
output:
    default_format: text
    json_pretty: true
