git:
    default_branch: main
worktree:
    enabled: true
    base_dir: ./.worktrees
    init_commands:
        - git status
    auto_operations:
        create_on_start: true
        remove_on_close: true
        cleanup_orphaned: true
tickets:
    dir: tickets
    todo_dir: todo
    doing_dir: doing
    archive_dir: done
    template: |-
        # 概要

        [ここにチケットの概要を記述]

        ## タスク
        - [ ] タスク1
        - [ ] タスク2
        - [ ] タスク3

        ## 技術仕様

        [必要に応じて技術的な詳細を記述]

        ## メモ

        [追加の注意事項やメモ]
output:
    default_format: text
    json_pretty: true
