name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.25'

      - name: Run tests
        run: make test

      - name: Build release archives
        run: make release-archives

      - name: Create Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt
          body: |
            ## Installation

            ### Linux
            ```bash
            # AMD64
            curl -L https://github.com/yshrsmz/ticketflow/releases/download/${{ github.ref_name }}/ticketflow-${{ github.ref_name }}-linux-amd64.tar.gz | tar xz
            sudo mv ticketflow /usr/local/bin/

            # ARM64
            curl -L https://github.com/yshrsmz/ticketflow/releases/download/${{ github.ref_name }}/ticketflow-${{ github.ref_name }}-linux-arm64.tar.gz | tar xz
            sudo mv ticketflow /usr/local/bin/
            ```

            ### macOS
            ```bash
            # Intel
            curl -L https://github.com/yshrsmz/ticketflow/releases/download/${{ github.ref_name }}/ticketflow-${{ github.ref_name }}-darwin-amd64.tar.gz | tar xz
            sudo mv ticketflow /usr/local/bin/

            # Apple Silicon
            curl -L https://github.com/yshrsmz/ticketflow/releases/download/${{ github.ref_name }}/ticketflow-${{ github.ref_name }}-darwin-arm64.tar.gz | tar xz
            sudo mv ticketflow /usr/local/bin/
            ```

            ### Windows
            Download the Windows zip file and extract to a directory in your PATH.

            ## Checksums
            See `checksums.txt` for SHA256 checksums of all release files.
