name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: '1.25.x'

    - name: Cache Go modules
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test

    - name: Run integration tests
      run: make test-integration

    - name: Check code formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "The following files need formatting:"
          gofmt -s -l .
          exit 1
        fi

    - name: Run go vet
      run: make vet

    - name: Generate coverage report
      if: github.event_name == 'pull_request'
      run: |
        go test -coverprofile=coverage.out -covermode=atomic ./...
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
        
        # Generate detailed coverage by package
        echo "COVERAGE_DETAILS<<EOF" >> $GITHUB_ENV
        go tool cover -func=coverage.out | grep -v "total:" | while IFS=$'\t' read -r file func coverage; do
          if [[ -n "$coverage" ]]; then
            printf "| %-80s %-20s | %7s |\n" "$file" "$func" "$coverage"
          fi
        done | sort >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Post coverage comment
      if: github.event_name == 'pull_request'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const coverage = process.env.COVERAGE;
          const details = process.env.COVERAGE_DETAILS;
          
          // Determine coverage emoji and color
          const coverageFloat = parseFloat(coverage);
          let emoji = '🔴';
          let color = 'red';
          if (coverageFloat >= 80) {
            emoji = '🟢';
            color = 'green';
          } else if (coverageFloat >= 60) {
            emoji = '🟡';
            color = 'yellow';
          }
          
          const comment = `## ${emoji} Test Coverage Report
          
          **Total Coverage:** **${coverage}**
          
          <details>
          <summary>Coverage by Package</summary>
          
          | Package | Coverage |
          |---------|----------|
          ${details}
          
          </details>
          
          ---
          <sub>Coverage generated by ticketflow CI</sub>`;
          
          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('Test Coverage Report')
          );
          
          if (botComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: comment
            });
          } else {
            // Create new comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
          }

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: '1.25.x'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      with:
        version: latest
